In [58]:
#Import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [59]:
#Read file. Establish that the file is being read properly with a sample of 5 indexes
purchasing_data = pd.read_json("purchase_data.json")
purchasing_data.head()

,Age,Gender,Item ID,Item Name,Price,SN
0,38,Male,165,Bone Crushing Silver Skewer,3.37,Aelalis34
1,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",2.32,Eolo46
2,34,Male,174,Primitive Blade,2.46,Assastnya25
3,21,Male,92,Final Critic,1.36,Pheusrical25
4,23,Male,63,Stormfury Mace,1.27,Aela59

In [60]:
#Show columns
print(purchasing_data.columns)
print(purchasing_data.count())

Index(['Age', 'Gender', 'Item ID', 'Item Name', 'Price', 'SN'], dtype='object')
Age          780
Gender       780
Item ID      780
Item Name    780
Price        780
SN           780
dtype: int64

In [140]:
#Find the amount of players

total_players = pd.DataFrame(purchasing_data)
total_players = (purchasing_data.index)
total_players = pd.DataFrame(total_players)

print ("Total Players: " + str(total_players.count()))

Total Players: 0    780
dtype: int64

In [141]:
#Purchasing Analysis Tool

#Unique Items
unique_amount = purchasing_data['Item ID'].unique()
print ("Amount of Unique Items: " + str(len(pd.value_counts(unique_amount))))

#Total Revenue
total_revenue = (purchasing_data["Price"].sum()) 
print ("Total Revenue: " + str(total_revenue))

#Average Purchase Price
avg_purchase_price = (total_revenue/total_players.count())
avg_purchase_price = (str(avg_purchase_price))
print("Average Purchase Price: " + (avg_purchase_price))

#Total Number of Purchases
total_purchases = purchasing_data['Price'].count()
print ("Total number of purchases: " + str(total_purchases))

Amount of Unique Items: 183
Total Revenue: 2286.3299999999963
Average Purchase Price: 0    2.931192
dtype: float64
Total number of purchases: 780

In [63]:
# Find the percentage and count of gender

#Male % & Count
male_p = (purchasing_data["Gender"] == "Male").sum()
male_percentage = male_p/780
male_count = male_percentage*780
print(male_percentage)
print(male_count)

#Female % & Count
female_p = (purchasing_data["Gender"] == "Female").sum()
female_percentage = female_p/780
female_count = female_percentage*780
print(female_percentage)
print(female_count)

#Non-Disclosed % & Count
non_p = (purchasing_data["Gender"] == "Other / Non-Disclosed").sum()
nd_percentage = non_p/780
nd_count = nd_percentage*780
print(nd_percentage)
print(nd_count)

0.811538461538
633.0
0.174358974359
136.0
0.0141025641026
11.0

In [64]:
# Purchase Analysis by Gender

# Created a new data frame
gender_purchase = purchasing_data[["Gender", "Item Name","Price"]]
gender_purchase = pd.DataFrame(gender_purchase)
print(gender_purchase.tail(3))
print(" ")

# Average Purchase Price
m_p_c = (purchasing_data["Gender"] == "Male").sum()
male_app = total_revenue/m_p_c

f_p_c = (purchasing_data["Gender"] == "Female").sum()
female_app = total_revenue/f_p_c

n_p_c = (purchasing_data["Gender"] == "Other / Non-Disclosed").sum()
nd_app = total_revenue/n_p_c

print(" ")
print("The Average Purchase Price for Males: ", male_app)
print("The Average Purchase Price for Females: ", female_app)
print("The Average Purchase Price for Non-Disclosed: ", nd_app)
print(" ")

#Purchase Count

print ("Purchase count for Males: ", m_p_c)
print ("Purchase count for Females: ", f_p_c)
print ("Purchase count for Non-Disclosed: ", n_p_c)
print(" ")


#Total Purchase Value

#Nominal Purchase Value

     Gender                          Item Name  Price
777    Male  Heartstriker, Legacy of the Light   4.15
778    Male            Brutality Ivory Warmace   1.72
779  Female          Splitter, Foe Of Subtlety   3.61


The Average Purchase Price for Males:  3.6118957346
The Average Purchase Price for Females:  16.81125
The Average Purchase Price for Non-Disclosed:  207.848181818

Purchase count for Males:  633
Purchase count for Females:  136
Purchase count for Non-Disclosed:  11

In [65]:
#male_p = (purchasing_data["Gender"] == "Male").sum()
#non_p = (purchasing_data["Gender"] == "Other / Non-Disclosed").sum()
#non_p

In [66]:
#Age Demographics

bins = [0, 10, 20, 30, 40, 50, 60]
group_labels = [" > 10", "10 to 15", "15 to 19", "20 to 29", "30 to 49", "50 < "]

pd.cut(purchasing_data["Age"], bins, labels = group_labels)


purchasing_data["Age Range"] = pd.cut(purchasing_data["Age"], bins, labels = group_labels)
#print(purchasing_data.head())


#Purchase Count

purchase_dem = purchasing_data.groupby("Age Range").count()
purchase_dem = purchasing_data[['Age Range', 'Item Name']]
purchase_dem = purchase_dem.groupby("Age Range").count()
purchase_dem = purchase_dem.rename(columns = {'Item Name': 'Item Count'})
purchase_dem = pd.DataFrame(purchase_dem)

print(purchase_dem)


#Average Purchase Count

purchase_c = purchasing_data.groupby("Age Range")
purchase_c = purchase_c.sum()
purchase_c = pd.DataFrame(purchase_c)
print(purchase_c)

purchase_join = purchase_dem.join(purchase_c)
print(purchase_join)

purchase_join["Average Purchase Count"] = purchase_join["Price"]/purchase_join["Item Count"]
del purchase_join["Item Count"]
del purchase_join["Age"]
del purchase_join["Item ID"]
del purchase_join["Price"]

print(purchase_join)


#Total Purchase Value

tpv = purchasing_data.groupby("Age Range").sum()
del tpv["Age"]
del tpv["Item ID"]
ad_tpv = tpv.rename(columns = {'Price': 'Total Purchase Value'})
print(ad_tpv)

#Normalized Totals

           Item Count
Age Range
 > 10              32
10 to 15          262
15 to 19          381
20 to 29          102
30 to 49            3
50 <                0
              Age  Item ID    Price
Age Range
 > 10       251.0   2663.0    96.62
10 to 15   4558.0  22957.0   752.89
15 to 19   9205.0  34577.0  1122.43
20 to 29   3585.0  10721.0   305.75
30 to 49    130.0    291.0     8.64
50 <          NaN      NaN      NaN
           Item Count     Age  Item ID    Price
Age Range
 > 10              32   251.0   2663.0    96.62
10 to 15          262  4558.0  22957.0   752.89
15 to 19          381  9205.0  34577.0  1122.43
20 to 29          102  3585.0  10721.0   305.75
30 to 49            3   130.0    291.0     8.64
50 <                0     NaN      NaN      NaN
           Average Purchase Count
Age Range
 > 10                    3.019375
10 to 15                 2.873626
15 to 19                 2.946010
20 to 29                 2.997549
30 to 49                 2.880000
50 <                          NaN
           Total Purchase Value
Age Range
 > 10                     96.62
10 to 15                 752.89
15 to 19                1122.43
20 to 29                 305.75
30 to 49                   8.64
50 <                        NaN

In [69]:
#Top Spenders by SN

SN_df = purchasing_data.groupby("SN").sum()
SN_df_ts =purchasing_data.groupby("SN").sum()
del SN_df_ts["Item ID"]
del SN_df_ts["Age"]
tp_sn = SN_df_ts.sort_values('Price').tail()
#print(tp_sn)

#Purchase Count

SN_df_pc = purchasing_data.groupby("SN").count()
SN_df_pc = SN_df_pc.drop(["Age","Gender","Item Name","Age Range","Price"], axis = 1)
pc_sn = SN_df_pc.sort_values("Item ID").tail()
print(pc_sn)

#Average Purchase Price

SN_apc = SN_apc.rename(columns = {'Price': 'Average Purchase Price'})
SN_apc = SN_df.sort_values('Price').tail().sum()
del SN_apc["Age"]
del SN_apc["Item ID"]
#print("The average purchase price for the top 5 SN's:", SN_apc/5)

#Total Pruchase Value

#print(SN_apc)

             Item ID
SN
Sondastan54        4
Qarwen67           4
Mindimnya67        4
Hailaphos89        4
Undirrala66        5

NameError: name 'SN_apc' is not defined

In [85]:
#Most popular items

#Item Name
mpi = purchasing_data.groupby("Item Name").count().tail()
mpi = mpi.sort_values("Item ID").tail()
mpi.drop(['Age', 'Gender', 'Item ID', 'Price', 'Age Range'], axis=1, inplace=True)
#print(mpi)

#Item ID
mpi_id = purchasing_data.groupby("Item ID").count().tail()
mpi_id.drop(['Age', 'Gender', 'Item Name', 'Price', 'Age Range'], axis=1, inplace=True)
#print(mpi_id)

#Item Price

mpi_ip = purchasing_data.groupby("Item Name").sum()
#mpi_ip.drop(['Age', 'Gender', 'Item Name', 'Price', 'Age Range'], axis=1, inplace=True)
mpi_ip = mpi_ip.sort_values('Price').tail()
mpi_ip

#Total Purchase Value

mpi_tpv = mpi_ip.sum()
mpi_tpv = mpi_tpv.drop(["Age", "Item ID"])
#print(mpi_tpv)

#Total Purchase Count

mpi_tpc = purchasing_data.groupby("Item Name").count()
mpi_tpc.sort_values('SN').tail().sum()
mpi_tpc.drop(['Age', 'Gender', 'SN', 'Price', 'Age Range'], axis=1, inplace=True)
mpi_tpc = mpi_tpc.sort_values('Item ID').tail()
mpi_tpc

                                      Item ID
Item Name
Woeful Adamantite Claymore                  9
Stormcaller                                10
Arcane Gem                                 11
Betrayal, Whisper of Grieving Widows       11
Final Critic                               14

In [139]:
#Most profitable items

#By Item ID

#purchasing_data.head()
#purchasing_data.groupby("Item ID").count().tail()
#most_profit_id = purchasing_data[["Item Name","Item ID", "Price"]]
#most_profit_id

#most_profit_id

#most_profit_id = most_profit_id.sort_values("Price").tail()
#most_profit_id.sort_values("Item ID")











pd_df1 = purchasing_data.groupby(["Item Name", "Item ID"], as_index = True)
pd_df1.count()
#pd_df1.agg({Price':[np.size]}).head(5)

                                                  Age  Gender  Price  SN  \
Item Name                                Item ID
Abyssal Shard                            162        3       3      3   3
Aetherius, Boon of the Blessed           137        4       4      4   4
Agatha                                   120        5       5      5   5
Alpha                                    130        7       7      7   7
Alpha, Oath of Zeal                      79         7       7      7   7
Alpha, Reach of Ending Hope              47         6       6      6   6
Amnesia                                  22         6       6      6   6
Apocalyptic Battlescythe                 93         4       4      4   4
Arcane Gem                               84        11      11     11  11
Avenger                                  102        6       6      6   6
Azurewrath                               160        5       5      5   5
Betrayal, Whisper of Grieving Widows     39        11      11     11  11
Betrayer                                 90         3       3      3   3
Blade of the Grave                       172        7       7      7   7
Blazefury, Protector of Delusions        89         2       2      2   2
Blazeguard, Reach of Eternity            128        6       6      6   6
Blindscythe                              100        5       5      5   5
Blood Infused Guardian                   144        5       5      5   5
Blood-Forged Skeletal Spine              96         2       2      2   2
Bloodlord's Fetish                       4          1       1      1   1
Bone Crushing Silver Skewer              165        3       3      3   3
Bonecarvin Battle Axe                    44         8       8      8   8
Brimstone                                11         7       7      7   7
Brutality Ivory Warmace                  75         4       4      4   4
Celeste                                  91         6       6      6   6
Celeste, Incarnation of the Corrupted    67         4       4      4   4
Chaos, Ender of the End                  29         3       3      3   3
Conqueror Adamantite Mace                65         8       8      8   8
Crucifer                                 1          4       4      4   4
                                         23         4       4      4   4
...                                               ...     ...    ...  ..
Thorn, Conqueror of the Corrupted        9          2       2      2   2
Thorn, Satchel of Dark Souls             7          6       6      6   6
Thunderfury Scimitar                     163        3       3      3   3
Toothpick                                182        5       5      5   5
Torchlight, Bond of Storms               18         7       7      7   7
Tranquility, Razor of Black Magic        149        2       2      2   2
Trickster                                31         9       9      9   9
Twilight's Carver                        123        5       5      5   5
Undead Crusader                          134        4       4      4   4
Unending Tyranny                         122        3       3      3   3
Unholy Wand                              26         4       4      4   4
Vengeance Cleaver                        53         3       3      3   3
Venom Claymore                           124        6       6      6   6
Verdict                                  2          1       1      1   1
Victor Iron Spikes                       66         7       7      7   7
Vindictive Glass Edge                    55         2       2      2   2
War-Forged Gold Deflector                155        3       3      3   3
Warmonger, Gift of Suffering's End       148        6       6      6   6
Warped Diamond Crusader                  135        3       3      3   3
Warped Fetish                            24         2       2      2   2
Warped Iron Scimitar                     146        2       2      2   2
Whistling Mithril Warblade               125        4       4      4   4
Winter's Bite                            72         2       2      2   2
Winterthorn, Defender of Shifting Worlds 177        4       4      4   4
Woeful Adamantite Claymore               175        9       9      9   9
Wolf                                     60         5       5      5   5
Wolf, Promise of the Moonwalker          179        7       7      7   7
Worldbreaker                             112        2       2      2   2
Yearning Crusher                         74         2       2      2   2
Yearning Mageblade                       114        4       4      4   4

                                                  Age Range
Item Name                                Item ID
Abyssal Shard                            162              3
Aetherius, Boon of the Blessed           137              4
Agatha                                   120              5
Alpha                                    130              7
Alpha, Oath of Zeal                      79               7
Alpha, Reach of Ending Hope              47               6
Amnesia                                  22               6
Apocalyptic Battlescythe                 93               4
Arcane Gem                               84              11
Avenger                                  102              6
Azurewrath                               160              5
Betrayal, Whisper of Grieving Widows     39              11
Betrayer                                 90               3
Blade of the Grave                       172              7
Blazefury, Protector of Delusions        89               2
Blazeguard, Reach of Eternity            128              6
Blindscythe                              100              5
Blood Infused Guardian                   144              5
Blood-Forged Skeletal Spine              96               2
Bloodlord's Fetish                       4                1
Bone Crushing Silver Skewer              165              3
Bonecarvin Battle Axe                    44               8
Brimstone                                11               7
Brutality Ivory Warmace                  75               4
Celeste                                  91               6
Celeste, Incarnation of the Corrupted    67               4
Chaos, Ender of the End                  29               3
Conqueror Adamantite Mace                65               8
Crucifer                                 1                4
                                         23               4
...                                                     ...
Thorn, Conqueror of the Corrupted        9                2
Thorn, Satchel of Dark Souls             7                6
Thunderfury Scimitar                     163              3
Toothpick                                182              5
Torchlight, Bond of Storms               18               7
Tranquility, Razor of Black Magic        149              2
Trickster                                31               9
Twilight's Carver                        123              5
Undead Crusader                          134              4
Unending Tyranny                         122              3
Unholy Wand                              26               4
Vengeance Cleaver                        53               3
Venom Claymore                           124              6
Verdict                                  2                1
Victor Iron Spikes                       66               7
Vindictive Glass Edge                    55               2
War-Forged Gold Deflector                155              3
Warmonger, Gift of Suffering's End       148              6
Warped Diamond Crusader                  135              3
Warped Fetish                            24               2
Warped Iron Scimitar                     146              2
Whistling Mithril Warblade               125              4
Winter's Bite                            72               2
Winterthorn, Defender of Shifting Worlds 177              4
Woeful Adamantite Claymore               175              9
Wolf                                     60               5
Wolf, Promise of the Moonwalker          179              7
Worldbreaker                             112              2
Yearning Crusher                         74               2
Yearning Mageblade                       114              4

[183 rows x 5 columns]

In [110]:
purchasing_data.columns

Index(['Age', 'Gender', 'Item ID', 'Item Name', 'Price', 'SN', 'Age Range'], dtype='object')

In [122]:
purchasing_data.head(3)

,Age,Gender,Item ID,Item Name,Price,SN,Age Range
0,38,Male,165,Bone Crushing Silver Skewer,3.37,Aelalis34,20 to 29
1,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",2.32,Eolo46,15 to 19
2,34,Male,174,Primitive Blade,2.46,Assastnya25,20 to 29